<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
    <CS2ToolPath Condition="'$(CS2ToolPath)' == ''">$(CSII_TOOLPATH)</CS2ToolPath>
    <PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
    <Version>0.2.1-beta.1</Version>
    <AssemblyVersion>0.2.1.0</AssemblyVersion>
    <FileVersion>0.2.1.0</FileVersion>
    <InformationalVersion>0.2.1-beta.1</InformationalVersion>
  </PropertyGroup>
  <Import Project="$(CS2ToolPath)\Mod.props" />
  <Import Project="$(CS2ToolPath)\Mod.targets" />
  <ItemGroup>
    <Analyzer Remove="$(EntityPackagePath)\*.dll" />
    <Reference Include="Game"><Private>false</Private></Reference>
    <Reference Include="Colossal.Core"><Private>false</Private></Reference>
    <Reference Include="Colossal.Logging"><Private>false</Private></Reference>
    <Reference Include="Colossal.Localization"><Private>false</Private></Reference>
    <Reference Include="Colossal.UI.Binding"><Private>false</Private></Reference>
    <Reference Include="Colossal.Mathematics"><Private>false</Private></Reference>
    <Reference Include="Colossal.IO.AssetDatabase"><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><Private>false</Private></Reference>
    <Reference Include="UnityEngine.JSONSerializeModule"><Private>false</Private></Reference>
    <Reference Include="Unity.Entities"><Private>false</Private></Reference>
    <Reference Include="Unity.Collections"><Private>false</Private></Reference>
    <Reference Include="Unity.Mathematics"><Private>false</Private></Reference>
  </ItemGroup>
  <Target Name="BuildUI" BeforeTargets="BeforeBuild">
    <Exec WorkingDirectory="UI" Command="npm run build" />
  </Target>
  <Target Name="DeployEventEngineFiles" AfterTargets="Build">
    <ItemGroup>
      <EventEngineFiles Include="UI\dist\EventEngine.mjs;mod.json" />
      <EventEngineImages Include="UI\dist\images\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(EventEngineFiles)" DestinationFolder="$(DeployDir)" SkipUnchangedFiles="false" />
    <Copy SourceFiles="@(EventEngineImages)" DestinationFolder="$(DeployDir)\images" SkipUnchangedFiles="false" Condition="Exists('UI\dist\images')" />
    <Delete Files="$(DeployDir)\EventEngine_win_x86_64.dll;$(DeployDir)\EventEngine_mac_x86_64.bundle;$(DeployDir)\EventEngine_linux_x86_64.so;$(DeployDir)\EventEngine.pdb" />
  </Target>
</Project>
